// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOQ1KgmgpOTG0SSh82BBDcDdIFMyZFbPM',
    appId: '1:139691558685:web:c52989cf3361e47ee003f4',
    messagingSenderId: '139691558685',
    projectId: 'lineleap-dev',
    authDomain: 'lineleap-dev.firebaseapp.com',
    storageBucket: 'lineleap-dev.appspot.com',
    measurementId: 'G-EHYP08N2NS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN8brZe25FFWhwGkBN8GkdygEeyZ_vi6M',
    appId: '1:139691558685:android:f93711d857705653e003f4',
    messagingSenderId: '139691558685',
    projectId: 'lineleap-dev',
    storageBucket: 'lineleap-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcOWrg2Cnyi4vuYowvlk-puSGjuYKfX-M',
    appId: '1:139691558685:ios:670e72729d2edacce003f4',
    messagingSenderId: '139691558685',
    projectId: 'lineleap-dev',
    storageBucket: 'lineleap-dev.appspot.com',
    androidClientId: '139691558685-497o6bhrnqc5cup5for65mrkvr14ivn0.apps.googleusercontent.com',
    iosClientId: '139691558685-9csn0f3b1qod4nob7qessj06n8o1v506.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcOWrg2Cnyi4vuYowvlk-puSGjuYKfX-M',
    appId: '1:139691558685:ios:3f31108f1affa3f7e003f4',
    messagingSenderId: '139691558685',
    projectId: 'lineleap-dev',
    storageBucket: 'lineleap-dev.appspot.com',
    androidClientId: '139691558685-497o6bhrnqc5cup5for65mrkvr14ivn0.apps.googleusercontent.com',
    iosClientId: '139691558685-cvag4tubug42q101hbumqm3t6lbrbmr3.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
